import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Zap, Shield, CheckCircle, Star, Globe, Lock, BarChart3 } from "lucide-react";
import { Link } from "wouter";

export default function Integrations() {
  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <Link href="/">
            <Button variant="ghost" className="mb-4" data-testid="back-link">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Integrations & Features</h1>
          <p className="text-lg text-gray-600 max-w-3xl">
            Connect SharpSend with your existing email marketing stack and unlock the full power 
            of AI-driven newsletter optimization for financial publishers.
          </p>
        </div>

        {/* Core Features Overview */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">Core Platform Features</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Zap className="w-6 h-6 text-primary-600" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">AI Content Generation</h3>
                <p className="text-gray-600">
                  Generate personalized subject lines, email content, and segment recommendations 
                  using advanced AI models trained on financial content.
                </p>
              </CardContent>
            </Card>

            <Card className="text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <BarChart3 className="w-6 h-6 text-green-600" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Revenue Attribution</h3>
                <p className="text-gray-600">
                  Track every dollar generated by your newsletters with advanced attribution 
                  modeling and 7-day post-click revenue tracking.
                </p>
              </CardContent>
            </Card>

            <Card className="text-center">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Globe className="w-6 h-6 text-blue-600" />
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Automated Pixel Management</h3>
                <p className="text-gray-600">
                  Automatically insert and manage tracking pixels across all email campaigns 
                  without manual intervention or technical overhead.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* ESP Integrations */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">Email Service Provider Integrations</h2>
          
          <div className="grid lg:grid-cols-2 gap-8 mb-12">
            {/* Basic Connectors */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <CheckCircle className="w-5 h-5 mr-2 text-green-600" />
                  Basic Connectors (All Plans)
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-blue-500 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">M</div>
                    <span className="font-medium">Mailchimp</span>
                  </div>
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-green-500 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">S</div>
                    <span className="font-medium">SendGrid</span>
                  </div>
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-purple-500 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">K</div>
                    <span className="font-medium">Klaviyo</span>
                  </div>
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-orange-500 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">A</div>
                    <span className="font-medium">ActiveCampaign</span>
                  </div>
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-red-500 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">C</div>
                    <span className="font-medium">ConvertKit</span>
                  </div>
                  <div className="flex items-center p-3 bg-gray-50 rounded-lg">
                    <div className="w-8 h-8 bg-blue-600 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">A</div>
                    <span className="font-medium">AWeber</span>
                  </div>
                </div>
                <p className="text-sm text-gray-600">
                  Easy setup with OAuth authentication and real-time synchronization of campaigns, 
                  subscribers, and performance metrics.
                </p>
              </CardContent>
            </Card>

            {/* Premium Connectors */}
            <Card className="border-2 border-primary-200">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Star className="w-5 h-5 mr-2 text-primary-600" />
                  Premium Connectors (Growth+)
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 gap-4 mb-6">
                  <div className="flex items-center p-3 bg-primary-50 rounded-lg">
                    <div className="w-8 h-8 bg-orange-600 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">H</div>
                    <span className="font-medium">HubSpot Marketing</span>
                  </div>
                  <div className="flex items-center p-3 bg-primary-50 rounded-lg">
                    <div className="w-8 h-8 bg-blue-700 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">S</div>
                    <span className="font-medium">Salesforce Marketing Cloud</span>
                  </div>
                  <div className="flex items-center p-3 bg-primary-50 rounded-lg">
                    <div className="w-8 h-8 bg-purple-600 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">M</div>
                    <span className="font-medium">Marketo Engage</span>
                  </div>
                  <div className="flex items-center p-3 bg-primary-50 rounded-lg">
                    <div className="w-8 h-8 bg-green-700 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">P</div>
                    <span className="font-medium">Pardot</span>
                  </div>
                  <div className="flex items-center p-3 bg-primary-50 rounded-lg">
                    <div className="w-8 h-8 bg-red-600 rounded mr-3 flex items-center justify-center text-white text-xs font-bold">E</div>
                    <span className="font-medium">Eloqua</span>
                  </div>
                </div>
                <p className="text-sm text-gray-600">
                  Advanced enterprise integrations with custom field mapping, automated workflows, 
                  and dedicated customer success support.
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Integration Features */}
          <div className="bg-gradient-to-r from-primary-50 to-blue-50 rounded-xl p-8">
            <h3 className="text-xl font-semibold text-gray-900 mb-6 text-center">Integration Capabilities</h3>
            <div className="grid md:grid-cols-4 gap-6">
              <div className="text-center">
                <div className="w-10 h-10 bg-primary-600 rounded-full flex items-center justify-center mx-auto mb-3">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <h4 className="font-medium text-gray-900 mb-1">Real-time Sync</h4>
                <p className="text-sm text-gray-600">Instant data synchronization</p>
              </div>
              <div className="text-center">
                <div className="w-10 h-10 bg-green-600 rounded-full flex items-center justify-center mx-auto mb-3">
                  <CheckCircle className="w-5 h-5 text-white" />
                </div>
                <h4 className="font-medium text-gray-900 mb-1">Automated Setup</h4>
                <p className="text-sm text-gray-600">One-click integration setup</p>
              </div>
              <div className="text-center">
                <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-3">
                  <BarChart3 className="w-5 h-5 text-white" />
                </div>
                <h4 className="font-medium text-gray-900 mb-1">Unified Reporting</h4>
                <p className="text-sm text-gray-600">Cross-platform analytics</p>
              </div>
              <div className="text-center">
                <div className="w-10 h-10 bg-purple-600 rounded-full flex items-center justify-center mx-auto mb-3">
                  <Globe className="w-5 h-5 text-white" />
                </div>
                <h4 className="font-medium text-gray-900 mb-1">Multi-account</h4>
                <p className="text-sm text-gray-600">Manage multiple accounts</p>
              </div>
            </div>
          </div>
        </section>

        {/* CRM Integrations */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">CRM & Analytics Integrations</h2>
          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-center">Customer Relationship</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-blue-600 rounded mr-3"></div>
                    <span className="text-sm">Salesforce CRM</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-orange-600 rounded mr-3"></div>
                    <span className="text-sm">HubSpot CRM</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-green-600 rounded mr-3"></div>
                    <span className="text-sm">Pipedrive</span>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-center">Analytics Platforms</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-blue-500 rounded mr-3"></div>
                    <span className="text-sm">Google Analytics</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-purple-600 rounded mr-3"></div>
                    <span className="text-sm">Adobe Analytics</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-red-600 rounded mr-3"></div>
                    <span className="text-sm">Mixpanel</span>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-center">E-commerce</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-green-700 rounded mr-3"></div>
                    <span className="text-sm">Shopify</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-blue-800 rounded mr-3"></div>
                    <span className="text-sm">WooCommerce</span>
                  </div>
                  <div className="flex items-center p-2 bg-gray-50 rounded">
                    <div className="w-6 h-6 bg-orange-700 rounded mr-3"></div>
                    <span className="text-sm">BigCommerce</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* Security & Compliance */}
        <section className="mb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">Security & Compliance</h2>
          <div className="grid md:grid-cols-2 gap-8">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Shield className="w-5 h-5 mr-2 text-green-600" />
                  Data Security
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3">
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">SOC 2 Type II certified</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">End-to-end encryption (AES-256)</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">GDPR & CCPA compliant</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">Regular security audits</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">Role-based access controls</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Lock className="w-5 h-5 mr-2 text-blue-600" />
                  Email Deliverability
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3">
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">SPF, DKIM, DMARC validation</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">Automated reputation monitoring</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">Bounce & complaint handling</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">List hygiene recommendations</span>
                  </li>
                  <li className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-green-500 mr-3" />
                    <span className="text-gray-700">Inbox placement optimization</span>
                  </li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* Scalability */}
        <section className="mb-12">
          <Card className="bg-gradient-to-r from-primary-600 to-primary-800 text-white">
            <CardContent className="p-8">
              <div className="text-center mb-8">
                <h2 className="text-2xl font-bold mb-4">Enterprise-Grade Scalability</h2>
                <p className="text-primary-100 max-w-2xl mx-auto">
                  Built to handle the demanding requirements of large-scale financial publishers 
                  with millions of subscribers and complex attribution needs.
                </p>
              </div>
              <div className="grid md:grid-cols-3 gap-8">
                <div className="text-center">
                  <div className="text-3xl font-bold mb-2">99.9%</div>
                  <div className="text-primary-200">Uptime SLA</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold mb-2">10M+</div>
                  <div className="text-primary-200">Events per minute</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold mb-2">&lt;50ms</div>
                  <div className="text-primary-200">Average API response</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* CTA Section */}
        <div className="text-center bg-gray-100 rounded-xl p-8">
          <h3 className="text-2xl font-semibold text-gray-900 mb-4">Ready to Integrate?</h3>
          <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
            Our integration team will help you connect SharpSend with your existing tools 
            and have you up and running in under 24 hours.
          </p>
          <div className="flex justify-center space-x-4">
            <Button asChild>
              <Link href="/api-docs">View API Docs</Link>
            </Button>
            <Button variant="outline" asChild>
              <Link href="/contact">Talk to Integration Team</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}